<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>fileTypes</key>
	<array>
		<string>ttl</string>
	</array>
	<key>name</key>
	<string>Turtle</string>
	<key>patterns</key>
	<array>
		<dict>
			<key>begin</key>
			<string>([&lt;][^&gt;]+[&gt;])|(([\w]+[:])?[\w]+)</string>
			<key>end</key>
			<string>\.</string>
			<key>name</key>
			<string>meta.turtle.subject</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>include</key>
					<string>#triplestring</string>
				</dict>
				<dict>
					<key>include</key>
					<string>#doublestring</string>
				</dict>
			</array>
		</dict>
		<dict>
			<key>captures</key>
			<dict>
				<key>1</key>
				<dict>
					<key>name</key>
					<string>keyword.turtle.prefix</string>
				</dict>
				<key>2</key>
				<dict>
					<key>name</key>
					<string>variable.other.turtle.ns</string>
				</dict>
				<key>3</key>
				<dict>
					<key>name</key>
					<string>markup.underline.link.turtle.uri</string>
				</dict>
			</dict>
			<key>match</key>
			<string>(@prefix)[\s]+?([\w]+)[:][\s]+[&lt;]([^&gt;]+)[&gt;][\s]?[\.]</string>
			<key>name</key>
			<string>source.turtle.prefix</string>
		</dict>
	</array>
	<key>repository</key>
	<dict>
		<key>doublestring</key>
		<dict>
			<key>begin</key>
			<string>"</string>
			<key>end</key>
			<string>"</string>
			<key>name</key>
			<string>string.quoted.double.turtle</string>
			<key>patterns</key>
			<array>
				<dict>
					<key>match</key>
					<string>\\.</string>
					<key>name</key>
					<string>constant.character.escape.turtle</string>
				</dict>
			</array>
		</dict>
		<key>triplestring</key>
		<dict>
			<key>begin</key>
			<string>"""</string>
			<key>end</key>
			<string>"""</string>
			<key>name</key>
			<string>string.quoted.triple.turtle</string>
		</dict>
	</dict>
	<key>scopeName</key>
	<string>source.turtle</string>
	<key>uuid</key>
	<string>87318912-6F6A-4E86-A8A2-27164C26FEBD</string>
</dict>
</plist>
